 export const tableData = [
  {
    id: '1',
    tradeNumber: '001',
    portfolio: 'Company A Fund',
    counterParty: 'SG Bank',
    price: 1500,
  },
  {
    id: '2',
    tradeNumber: '002',
    portfolio: 'Company B Assets',
    counterParty: 'JP Bank6',
    price: 2000,
  },
  {
    id: '3',
    tradeNumber: '003',
    portfolio: 'Global Fund',
    counterParty: 'SG Securities',
    price: 1200,
  },
  {
    id: '4',
    tradeNumber: '004',
    portfolio: 'International Fund',
    counterParty: 'SG Holdings',
    price: -1500,
  },
  {
    id: '5',
    tradeNumber: '005',
    portfolio: 'Company C Equity',
    counterParty: 'FR Bank',
    price: 800,
  },
  {
    id: '6',
    tradeNumber: '006',
    portfolio: 'Global Fund',
    counterParty: 'SG Capital',
    price: 1100,
  },
  {
    id: '7',
    tradeNumber: '007',
    portfolio: 'Company A Equity',
    counterParty: 'SG Bank',
    price: -2000,
  },
  {
    id: '8',
    tradeNumber: '008',
    portfolio: 'Company D Fund',
    counterParty: 'US Bank',
    price: 300,
  },
];
